# Generated by Django 5.1.4 on 2025-01-14 13:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_match_team1_alter_match_team2'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='match',
            old_name='date',
            new_name='played_at',
        ),
        migrations.RemoveField(
            model_name='match',
            name='loser',
        ),
        migrations.RemoveField(
            model_name='match',
            name='score',
        ),
        migrations.AddField(
            model_name='match',
            name='team1_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='match',
            name='team1_set_scores',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='match',
            name='team2_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='match',
            name='team2_set_scores',
            field=models.JSONField(default=list),
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=100)),
                ('tournament_type', models.CharField(choices=[('BRACKET', 'Bracket'), ('AMERICANO', 'Americano')], default='BRACKET', max_length=10)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('matches', models.ManyToManyField(to='api.match')),
                ('teams', models.ManyToManyField(to='api.team')),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tournament_winner', to='api.team')),
            ],
        ),
    ]
