# Generated by Django 5.1.4 on 2025-01-19 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_tournament_tournament_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='score_team_1',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='score_team_2',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
